name: Auto-build HTML

on:
  push:
      branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "installing asciidoctor"
        sudo apt-get install asciidoctor ruby -y
        echo "Making deployment dir - docs/"
        mkdir docs
        echo "Add Training Plan to docs/"
        asciidoctor training-plan.adoc -o docs/training-plan.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: master